In [ ]:
# Import required libraries for data manipulation and analysis
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
upload=files.upload()

Saving Messy_Employment_India_Dataset (1).csv to Messy_Employment_India_Dataset (1).csv

**Load Dataset**

In [ ]:
# Load the messy employment dataset into a DataFrame
df = pd.read_csv("Messy_Employment_India_Dataset.csv")
df.head()       # Display first five records

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

**Understand Dataset Structure**

In [ ]:
df.shape   # Check the number of rows and columns in the dataset

(2000, 9)

In [ ]:
# Display dataset information including column names,non-null counts,data types
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB
None

In [ ]:
# View the data type of each column
print(df.dtypes)

Status                   object
Age Group                object
Education                object
Industry                 object
Location                 object
AI Risk                  object
Years of Experience     float64
Monthly Salary (INR)    float64
Date Recorded            object
dtype: object

In [ ]:
# Display all column names in the dataset
print(df.columns)

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')

**Identify and Handle Missing Values**

In [ ]:
# Check missing values in each column
df.isnull().sum()

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [ ]:
# Fill missing values in numerical columns using median
df["Years of Experience"] = df["Years of Experience"].fillna(df["Years of Experience"].median())
df["Monthly Salary (INR)"] = df["Monthly Salary (INR)"].fillna(df["Monthly Salary (INR)"].median())

In [ ]:
# Fill missing values in categorical columns using mode
categorical_cols = ["Status","Age Group","Education","Industry","Location","AI Risk"]
for i in categorical_cols:
    df[i] = df[i].fillna(df[i].mode()[0])

In [ ]:
# Verify missing values after treatment
df.isnull().sum()

Status                  0
Age Group               0
Education               0
Industry                0
Location                0
AI Risk                 0
Years of Experience     0
Monthly Salary (INR)    0
Date Recorded           0
dtype: int64

**Remove Duplicate Records**

In [ ]:
# Count duplicate records
print(df.duplicated().sum())

0

**Correct Inconsistent Formatting**

In [ ]:
# Remove leading and trailing spaces from text columns
text_cols = df.select_dtypes(include="object").columns
for i in text_cols:
    df[i] = df[i].str.strip()

In [ ]:
# Standardize status values
df["Status"] = df["Status"].str.lower()
df["Status"] = df["Status"].replace({"employed":"Employed","unemployed":"Unemployed"})

In [ ]:
# Standardize AI Risk values
df["AI Risk"] = df["AI Risk"].str.lower()
df["AI Risk"] = df["AI Risk"].replace({
    "low": "Low",
    "moderate": "Moderate",
    "medium": "Moderate",
    "high": "High"
})

In [ ]:
# Standardize age group formats
df["Age Group"] = df["Age Group"].replace({
    "25_34": "25-34",
    "18 to 24": "18-24",
    "35 - 44": "35-44"
})

In [ ]:
# Standardize education values
df["Education"] = df["Education"].replace({
    "high school": "High School",
    "Master": "Masters",
    "Ph.D": "PhD",
    "Bachelors": "Bachelor's"
})

In [ ]:
# Standardize industry names
df["Industry"] = df["Industry"].replace({"Tech": "Technology","Fintech": "Finance"})

**Fix Data Type**

In [ ]:
# Convert experience column to numeric type
df["Years of Experience"] = pd.to_numeric(
    df["Years of Experience"],
    errors="coerce"
)

In [ ]:
# Convert salary column to numeric type
df["Monthly Salary (INR)"] = pd.to_numeric(
    df["Monthly Salary (INR)"],
    errors="coerce"
)

In [ ]:
# Convert date column to datetime
df["Date Recorded"] = pd.to_datetime(
    df["Date Recorded"]
)

In [ ]:
# Verify data types
df.dtypes

Status                          object
Age Group                       object
Education                       object
Industry                        object
Location                        object
AI Risk                         object
Years of Experience            float64
Monthly Salary (INR)           float64
Date Recorded           datetime64[ns]
dtype: object

**Detect and Handle Outliers**

In [ ]:
# Handle outliers in Years of Experience and Salary using IQR
num_cols = ["Years of Experience", "Monthly Salary (INR)"]
for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])

**Rename and Standardize Column Names**

In [ ]:
# Standardize column names
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("(", "", regex=False)
      .str.replace(")", "", regex=False)
)

In [ ]:
# View updated column names
print(df.columns)

Index(['status', 'age_group', 'education', 'industry', 'location', 'ai_risk',
       'years_of_experience', 'monthly_salary_inr', 'date_recorded'],
      dtype='object')

**Validate Cleaned Data**

In [ ]:
# Check dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   status               2000 non-null   object
 1   age_group            2000 non-null   object
 2   education            2000 non-null   object
 3   industry             2000 non-null   object
 4   location             2000 non-null   object
 5   ai_risk              2000 non-null   object
 6   years_of_experience  2000 non-null   float64
 7   monthly_salary_inr   2000 non-null   float64
 8   date_recorded        2000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 140.8+ KB

In [ ]:
# Verify missing values
df.isnull().sum()

status                 0
age_group              0
education              0
industry               0
location               0
ai_risk                0
years_of_experience    0
monthly_salary_inr     0
date_recorded          0
dtype: int64

In [ ]:
# Verify duplicate records
print(df.duplicated().sum())

0

In [ ]:
# Display final shape
df.shape

(2000, 9)

**Export Cleaned Dataset**

In [ ]:
# Save cleaned dataset
df.to_csv("Cleaned_Employment_India_Dataset.csv", index=False)

# Download dataset
from google.colab import files
files.download("Cleaned_Employment_India_Dataset.csv")
print("Dataset exported and downloaded successfully!")

Dataset exported and downloaded successfully!